CREATE TABLE `item_review`(
  `item_id` INT NOT NULL,
  `action` VARCHAR(15) NULL DEFAULT NULL,
  `adventure` VARCHAR(45) NULL DEFAULT NULL,
  `animation` VARCHAR(45) NULL DEFAULT NULL,
  `childrens` VARCHAR(45) NULL DEFAULT NULL,
  `comedy` VARCHAR(45) NULL DEFAULT NULL,
  `crime` VARCHAR(45) NULL DEFAULT NULL,
  `documentary` VARCHAR(45) NULL DEFAULT NULL,
  `drama` VARCHAR(45) NULL DEFAULT NULL,
  `fantasy` VARCHAR(45) NULL DEFAULT NULL,
  `film_noir` VARCHAR(45) NULL DEFAULT NULL,
  `horror` VARCHAR(45) NULL DEFAULT NULL,
  `musical` VARCHAR(45) NULL DEFAULT NULL,
  `mystery` VARCHAR(45) NULL DEFAULT NULL,
  `romance` VARCHAR(45) NULL DEFAULT NULL,
  `sci_fi` VARCHAR(45) NULL DEFAULT NULL,
  `thriller` VARCHAR(45) NULL DEFAULT NULL,
  `war` VARCHAR(45) NULL DEFAULT NULL,
  `western` VARCHAR(45) NULL DEFAULT NULL,
  `family` VARCHAR(45) NULL DEFAULT NULL,
  `history` VARCHAR(45) NULL DEFAULT NULL,
  `reality_tv` VARCHAR(45) NULL DEFAULT NULL,
  `music` VARCHAR(45) NULL DEFAULT NULL,
  `foreign` VARCHAR(45) NULL DEFAULT NULL,
   PRIMARY KEY (`item_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
   
   
   CREATE TABLE `movies_title`(
  `movie_id` INT NOT NULL,
  `title` VARCHAR(500) NULL DEFAULT NULL,
     PRIMARY KEY (`movie_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
